name = "tdf-alerts-bot"
main = "worker/index.ts"
compatibility_date = "2026-05-23"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
persist = true
head_sampling_rate = 1

[vars]
GITHUB_REPOSITORY = "salmanrazzaq-94/tdf-offer-alerts"
GITHUB_REFRESH_REF = "main"

[triggers]
crons = ["*/10 * * * *", "0 13 * * *", "0 14 * * *"]

[[kv_namespaces]]
binding = "TDF_ALERTS"
id = "565f5f3899a547439f1ce155e9947971"
