export const cookieKey = "TDF_COOKIE";
export const cookieMetaKey = "TDF_COOKIE_META";
export const seenKey = "SEEN_OFFERS";
export const authStateKey = "AUTH_STATE";
export const healthStateKey = "HEALTH_STATE";
export const deltaLockKey = "DELTA_LOCK";
export const workerVersion = "2026-05-27.production-hardening-v1";
export const tdfOffersUrl = "https://nycgw47.tdf.org/TDFCustomOfferings/Current";
export const tdfPerformancesUrl = "https://nycgw47.tdf.org/TDFCustomOfferings/Current?handler=Performances";
export const tdfMemberHomeUrl = "https://my.tdf.org/";
export const authFailureNotifyIntervalMs = 12 * 60 * 60 * 1000;
export const browserbaseRefreshAttemptIntervalMs = 6 * 60 * 60 * 1000;
export const browserbaseDispatchFailureRetryMs = 30 * 60 * 1000;
export const staleSuccessAlertAfterMs = 30 * 60 * 1000;
export const deltaLockTtlMs = 8 * 60 * 1000;
export const cookieRefreshPersistIntervalMs = 60 * 60 * 1000;
export const healthStateWriteIntervalMs = 20 * 60 * 1000;
export const runLogSchemaVersion = 1;
